/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bd9f7481c75cea886dafb4dc3f7fd5fd)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	PASAY_APP_ENV: "development" | "production" | "local";
	PASAY_HEALTHCHECK_DB_CONNECTIVITY: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevelopmentEnv {
		HYPERDRIVE: Hyperdrive;
		PASAY_APP_ENV: "development";
		PASAY_HEALTHCHECK_DB_CONNECTIVITY: "false";
	}
	interface ProductionEnv {
		HYPERDRIVE: Hyperdrive;
		PASAY_APP_ENV: "production";
		PASAY_HEALTHCHECK_DB_CONNECTIVITY: "false";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PASAY_APP_ENV" | "PASAY_HEALTHCHECK_DB_CONNECTIVITY">> {}
}
