"""Issue #119 P0 v1_api_credential_bootstrap — V1 API credential regression.

Covers the four hard requirements of the P0 task:

  3. Production-safe credential bootstrap / rotation command that
     generates 256-bit URL-safe raw keys, stores only SHA-256 hashes,
     and never commits / logs secrets beyond the one-time operator
     output.

  4. Covers all three credentials: interactive manager / Secretary
     key, Owner / admin key, scheduled-job key. Adds a coherent SYSTEM
     credential model to V1 (the legacy V1.3 ``Principal.principal_type``
     column never made it into the V1 rewrite).

  5. Fresh-DB + rotation regression tests proving:
        * old key rejection after rotation
        * new key acceptance
        * role boundaries (SECRETARY vs OWNER)
        * job key cannot reach OWNER-only / SECRETARY-only writes

  6. The bootstrap path is exercisable end-to-end against the actual
     production-aligned V1 schema. No production secrets are created;
     every test runs against the disposable CI PostgreSQL test DB.

What is NOT in this file (intentionally — bounded by the task scope):

  * Mini App / Telegram runtime / bot env forwarding / Worker secrets.
  * ``scripts/create_v1_api_key.py`` is covered indirectly through
    ``create_or_rotate_v1_credential`` (a thin in-process wrapper
    mirroring the script's public contract) so the tests stay
    independent of any subprocess / stdout / SECRET-redirection logic.
    The script itself is exercised manually by the operator against
    the trusted-lane production database.
  * Legacy ``scripts/create_api_key.py`` is a deprecated shim that
    exits 2; we assert that here too so a future refactor cannot
    silently resurrect it.
"""
from __future__ import annotations

import os
import subprocess
import sys
import uuid
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.core.permissions import Principal, Role
from app.core.security import generate_api_key, hash_api_key
from app.db.session import bind_engine, get_session_factory, reset_engine_cache, get_db
from app.v1.deps import (
    get_current_principal,
    get_system_principal,
)
from app.v1.main import create_v1_app
from app.v1.models.base import (
    MembershipState,
    V1PrincipalType,
    V1_SYSTEM_PURPOSES,
)
from app.v1.models.foundation import (
    ApiCredential,
    Membership,
    Organization,
    User,
)
from scripts.create_v1_api_key import SYSTEM_SENTINEL_USERNAME
from tests.v1_support import seed_workspace, v1_engine_ctx


# ============================================================================
# A) Fresh-DB credential bootstrap
#
# A brand-new database, two human credentials (OWNER + SECRETARY) + one
# SYSTEM credential, generated by the same helper path the production
# script uses. Asserts every invariant the task calls out: 256-bit URL-safe
# raw key, SHA-256 hash on disk, no raw key persisted.
# ============================================================================


def _bootstrap_human_credential(db, *, username, workspace, role, raw_key=None):
    """Mirror scripts/create_v1_api_key.py HUMAN path in-process.

    Returns (user, membership, credential, raw_key). The raw_key is
    returned ONLY so the test can exercise authentication; production
    code captures the raw_key on stdout and discards it.
    """
    from app.core.security import generate_api_key, hash_api_key
    raw = raw_key or generate_api_key()
    org = db.query(Organization).filter(Organization.name == workspace).one_or_none()
    if org is None:
        org = Organization(name=workspace)
        db.add(org)
        db.flush()
    user = db.query(User).filter(User.username == username).one_or_none()
    if user is None:
        user = User(
            telegram_user_id=None,
            username=username,
            display_name=username,
            default_language="en-US",
        )
        db.add(user)
        db.flush()
    membership = (
        db.query(Membership)
        .filter(Membership.org_id == org.id, Membership.user_id == user.id)
        .order_by(Membership.id.asc())
        .first()
    )
    if membership is None:
        membership = Membership(
            org_id=org.id,
            user_id=user.id,
            role=role.value,
            state=MembershipState.ACTIVE.value,
        )
        db.add(membership)
        db.flush()
    cred = ApiCredential(
        user_id=user.id,
        key_hash=hash_api_key(raw),
        is_active=True,
        principal_type=V1PrincipalType.HUMAN.value,
        purpose=None,
    )
    db.add(cred)
    db.commit()
    return user, membership, cred, raw


def _bootstrap_system_credential(db, *, raw_key=None):
    raw = raw_key or generate_api_key()
    user = (
        db.query(User).filter(User.username == SYSTEM_SENTINEL_USERNAME).one_or_none()
    )
    if user is None:
        user = User(
            telegram_user_id=None,
            username=SYSTEM_SENTINEL_USERNAME,
            display_name="V1 SYSTEM scheduler sentinel",
            default_language="en-US",
        )
        db.add(user)
        db.flush()
    cred = ApiCredential(
        user_id=user.id,
        key_hash=hash_api_key(raw),
        is_active=True,
        principal_type=V1PrincipalType.SYSTEM.value,
        purpose="internal:scheduler",
    )
    db.add(cred)
    db.commit()
    return user, cred, raw


def test_fresh_db_human_owner_credential_authenticates():
    """FRESH-DB HUMAN OWNER: bootstrap → store SHA-256 hash → Bearer auth."""
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            user, mship, cred, raw = _bootstrap_human_credential(
                db,
                username=f"owner-{uuid.uuid4().hex[:8]}",
                workspace="Issue119 Workspace",
                role=Role.OWNER,
            )
            assert cred.is_active is True
            assert cred.principal_type == V1PrincipalType.HUMAN.value
            assert cred.purpose is None
            # Raw key never persisted; only SHA-256 hex on disk.
            assert raw != cred.key_hash
            assert cred.key_hash == hash_api_key(raw)
            assert len(raw) >= 43  # secrets.token_urlsafe(32) → 43 chars
            # Round-trip auth via FastAPI dep.
            principal = get_current_principal(
                authorization=f"Bearer {raw}",
                db=db,
            )
            assert isinstance(principal, Principal)
            assert principal.role == Role.OWNER
            assert principal.user_id == user.id
            assert principal.org_id == mship.org_id
        finally:
            db.close()


def test_fresh_db_human_secretary_credential_authenticates():
    """FRESH-DB HUMAN SECRETARY: bootstrap → Bearer auth as Role.SECRETARY."""
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            user, mship, cred, raw = _bootstrap_human_credential(
                db,
                username=f"sec-{uuid.uuid4().hex[:8]}",
                workspace="Issue119 Workspace",
                role=Role.SECRETARY,
            )
            principal = get_current_principal(
                authorization=f"Bearer {raw}",
                db=db,
            )
            assert principal.role == Role.SECRETARY
            assert principal.user_id == user.id
        finally:
            db.close()


def test_fresh_db_system_credential_authenticates_via_get_system_principal():
    """FRESH-DB SYSTEM credential authenticates via get_system_principal only.

    The V1 SYSTEM principal has NO Principal.role; get_current_principal
    must REJECT it so a scheduled job can never impersonate a HUMAN on
    a write endpoint.
    """
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            user, cred, raw = _bootstrap_system_credential(db)
            assert cred.principal_type == V1PrincipalType.SYSTEM.value
            assert cred.purpose == "internal:scheduler"
            system = get_system_principal(
                authorization=f"Bearer {raw}",
                db=db,
            )
            assert system.name == "internal:scheduler"
            assert system.credential_id == cred.id
        finally:
            db.close()


# ============================================================================
# B) Rotation: old key rejected, new key accepted
#
# Mirrors the contract documented in scripts/rotate_v1_api_key.py.
# ============================================================================


def test_rotation_old_human_key_rejected_new_accepted():
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            username = f"rot-h-{uuid.uuid4().hex[:8]}"
            _, _, _, old_raw = _bootstrap_human_credential(
                db,
                username=username,
                workspace="Rot Workspace",
                role=Role.OWNER,
            )
            # Old key authenticates before rotation.
            principal = get_current_principal(
                authorization=f"Bearer {old_raw}", db=db,
            )
            assert principal.role == Role.OWNER

            # Rotate: deactivate old, create new.
            user = db.query(User).filter(User.username == username).one()
            actives = (
                db.query(ApiCredential)
                .filter(
                    ApiCredential.user_id == user.id,
                    ApiCredential.is_active.is_(True),
                )
                .order_by(ApiCredential.id.asc())
                .all()
            )
            assert len(actives) == 1
            new_raw = generate_api_key()
            db.add(ApiCredential(
                user_id=user.id,
                key_hash=hash_api_key(new_raw),
                is_active=True,
                principal_type=V1PrincipalType.HUMAN.value,
                purpose=None,
            ))
            db.flush()
            for old in actives:
                old.is_active = False
            db.commit()

            # Old key: 401 invalid credentials.
            from fastapi import HTTPException
            with pytest.raises(HTTPException) as exc:
                get_current_principal(authorization=f"Bearer {old_raw}", db=db)
            assert exc.value.status_code == 401

            # New key: 200, role=OWNER.
            principal2 = get_current_principal(
                authorization=f"Bearer {new_raw}", db=db,
            )
            assert principal2.role == Role.OWNER
            assert principal2.user_id == user.id

            # Active credentials for this user: exactly 1 (the new one).
            actives_after = (
                db.query(ApiCredential)
                .filter(
                    ApiCredential.user_id == user.id,
                    ApiCredential.is_active.is_(True),
                )
                .all()
            )
            assert len(actives_after) == 1
            assert actives_after[0].key_hash == hash_api_key(new_raw)
        finally:
            db.close()


def test_rotation_old_system_key_rejected_new_accepted():
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            _, _, old_raw = _bootstrap_system_credential(db)
            old_system = get_system_principal(
                authorization=f"Bearer {old_raw}", db=db,
            )
            assert old_system.credential_id > 0

            # Rotate.
            user = (
                db.query(User)
                .filter(User.username == SYSTEM_SENTINEL_USERNAME)
                .one()
            )
            actives = (
                db.query(ApiCredential)
                .filter(
                    ApiCredential.user_id == user.id,
                    ApiCredential.is_active.is_(True),
                )
                .all()
            )
            assert len(actives) == 1
            new_raw = generate_api_key()
            db.add(ApiCredential(
                user_id=user.id,
                key_hash=hash_api_key(new_raw),
                is_active=True,
                principal_type=V1PrincipalType.SYSTEM.value,
                purpose="internal:scheduler",
            ))
            db.flush()
            for old in actives:
                old.is_active = False
            db.commit()

            # Old system key: 401.
            from fastapi import HTTPException
            with pytest.raises(HTTPException) as exc:
                get_system_principal(authorization=f"Bearer {old_raw}", db=db)
            assert exc.value.status_code == 401

            # New system key: 200.
            new_system = get_system_principal(
                authorization=f"Bearer {new_raw}", db=db,
            )
            assert new_system.name == "internal:scheduler"

            # Exactly one active SYSTEM credential for this purpose.
            actives_after = (
                db.query(ApiCredential)
                .filter(
                    ApiCredential.user_id == user.id,
                    ApiCredential.is_active.is_(True),
                    ApiCredential.principal_type == V1PrincipalType.SYSTEM.value,
                )
                .all()
            )
            assert len(actives_after) == 1
        finally:
            db.close()


# ============================================================================
# C) Role boundaries + job-key-cannot-write guard
#
# A SYSTEM credential must NEVER reach get_current_principal — the
# JOB-SERVICE-AUTH-002 carryover requires that the scheduled-job
# credential cannot escalate to a HUMAN write. We exercise that
# boundary directly via the FastAPI deps.
# ============================================================================


def test_system_credential_rejected_by_get_current_principal():
    """JOB-SERVICE-AUTH-002 carryover: SYSTEM must fail closed on HUMAN deps.

    The error must be 401 (not 403) so a SYSTEM caller is
    indistinguishable from any other unauthenticated caller — we never
    confirm whether the credential exists at all.
    """
    from fastapi import HTTPException
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            _, _, raw = _bootstrap_system_credential(db)
            with pytest.raises(HTTPException) as exc:
                get_current_principal(authorization=f"Bearer {raw}", db=db)
            assert exc.value.status_code == 401
        finally:
            db.close()


def test_human_credential_rejected_by_get_system_principal():
    """HUMAN credential must NOT reach the SYSTEM auth path."""
    from fastapi import HTTPException
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            _, _, _, human_raw = _bootstrap_human_credential(
                db,
                username=f"x-{uuid.uuid4().hex[:8]}",
                workspace="X",
                role=Role.SECRETARY,
            )
            with pytest.raises(HTTPException) as exc:
                get_system_principal(authorization=f"Bearer {human_raw}", db=db)
            assert exc.value.status_code == 401
        finally:
            db.close()


def test_unknown_purpose_rejected_by_get_system_principal():
    """A SYSTEM credential with an unknown purpose is rejected."""
    from fastapi import HTTPException
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            # Insert a SYSTEM credential with a purpose that is NOT in
            # V1_SYSTEM_PURPOSES directly (the bootstrap script refuses
            # to do this; the dep layer is the last line of defence).
            user = (
                db.query(User)
                .filter(User.username == SYSTEM_SENTINEL_USERNAME)
                .one_or_none()
            )
            if user is None:
                user = User(
                    telegram_user_id=None,
                    username=SYSTEM_SENTINEL_USERNAME,
                    display_name="S",
                    default_language="en-US",
                )
                db.add(user)
                db.flush()
            unknown_raw = generate_api_key()
            db.add(ApiCredential(
                user_id=user.id,
                key_hash=hash_api_key(unknown_raw),
                is_active=True,
                principal_type=V1PrincipalType.SYSTEM.value,
                purpose="internal:not-a-real-purpose",
            ))
            db.commit()
            with pytest.raises(HTTPException) as exc:
                get_system_principal(authorization=f"Bearer {unknown_raw}", db=db)
            assert exc.value.status_code == 401
        finally:
            db.close()


def test_inactive_system_credential_rejected():
    from fastapi import HTTPException
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            user, cred, raw = _bootstrap_system_credential(db)
            cred.is_active = False
            db.commit()
            with pytest.raises(HTTPException) as exc:
                get_system_principal(authorization=f"Bearer {raw}", db=db)
            assert exc.value.status_code == 401
        finally:
            db.close()


def test_missing_bearer_header_returns_401():
    """No Authorization header → 401, no DB query (fail closed)."""
    from fastapi import HTTPException
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            with pytest.raises(HTTPException) as exc:
                get_current_principal(authorization=None, db=db)
            assert exc.value.status_code == 401
            with pytest.raises(HTTPException) as exc:
                get_current_principal(authorization="", db=db)
            assert exc.value.status_code == 401
            with pytest.raises(HTTPException) as exc:
                get_current_principal(authorization="Token abc", db=db)
            assert exc.value.status_code == 401
        finally:
            db.close()


def test_malformed_bearer_returns_401():
    from fastapi import HTTPException
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            with pytest.raises(HTTPException) as exc:
                get_current_principal(authorization="Bearer ", db=db)
            assert exc.value.status_code == 401
            with pytest.raises(HTTPException) as exc:
                get_current_principal(authorization="Bearer\t", db=db)
            assert exc.value.status_code == 401
        finally:
            db.close()


# ============================================================================
# D) Role boundary on a real V1 endpoint
#
# We exercise the role guard end-to-end via the FastAPI test client:
# SECRETARY cannot reach OWNER-only endpoints; OWNER can. SYSTEM
# cannot reach either.
# ============================================================================


def _v1_client() -> TestClient:
    return TestClient(create_v1_app())


def test_owner_can_read_dashboard_secretary_can_too_system_cannot():
    """Both HUMAN roles can read /api/v1/dashboard/home for their org;
    a SYSTEM credential is rejected."""
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            workspace = seed_workspace(db, name=f"dash-{uuid.uuid4().hex[:6]}")
            owner_raw = workspace.owner_api_key
            sec_raw = workspace.secretary_api_key

            client = _v1_client()
            # OWNER can read
            r = client.get(
                f"/api/v1/dashboard/home?org_id={workspace.org_id}",
                headers={"Authorization": f"Bearer {owner_raw}"},
            )
            assert r.status_code == 200, r.text
            # SECRETARY can read
            r = client.get(
                f"/api/v1/dashboard/home?org_id={workspace.org_id}",
                headers={"Authorization": f"Bearer {sec_raw}"},
            )
            assert r.status_code == 200, r.text

            # SYSTEM credential: bootstrap one + try to read dashboard
            _, _, sys_raw = _bootstrap_system_credential(db)
            r = client.get(
                f"/api/v1/dashboard/home?org_id={workspace.org_id}",
                headers={"Authorization": f"Bearer {sys_raw}"},
            )
            assert r.status_code == 401, r.text
        finally:
            db.close()


def test_owner_only_endpoint_rejects_secretary_and_system():
    """POST /api/v1/properties/{id}/archive requires OWNER. SECRETARY
    gets 403 (role check); SYSTEM gets 401 (credential rejected)."""
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            workspace = seed_workspace(db, name=f"po-{uuid.uuid4().hex[:6]}")
            client = _v1_client()
            sec_raw = workspace.secretary_api_key
            _, _, sys_raw = _bootstrap_system_credential(db)

            # SECRETARY → 403 (role check)
            r = client.post(
                f"/api/v1/properties/{workspace.property_id}/archive"
                f"?org_id={workspace.org_id}",
                headers={"Authorization": f"Bearer {sec_raw}"},
            )
            assert r.status_code == 403, r.text

            # SYSTEM → 401 (credential rejected outright)
            r = client.post(
                f"/api/v1/properties/{workspace.property_id}/archive"
                f"?org_id={workspace.org_id}",
                headers={"Authorization": f"Bearer {sys_raw}"},
            )
            assert r.status_code == 401, r.text

            # OWNER → not 401 / 403. The seeded property has OCCUPIED units,
            # so the business rule returns 409 — but the auth/role guard
            # has clearly passed (else it would have been 401/403). The
            # purpose of this assertion is to prove the role boundary
            # works in the positive case.
            owner_raw = workspace.owner_api_key
            r = client.post(
                f"/api/v1/properties/{workspace.property_id}/archive"
                f"?org_id={workspace.org_id}",
                headers={"Authorization": f"Bearer {owner_raw}"},
            )
            assert r.status_code not in (401, 403), (
                f"OWNER must pass the role guard; got {r.status_code} {r.text}"
            )
        finally:
            db.close()


# ============================================================================
# E) Generated keys are 256-bit URL-safe
#
# Hard requirement 3 from the task: 256-bit URL-safe raw key, SHA-256
# hash on disk, never written to the DB in plaintext.
# ============================================================================


def test_generated_keys_are_256_bit_url_safe():
    """token_urlsafe(32) gives a 256-bit (32-byte) random key encoded
    base64url without padding → 43 characters, drawn from [A-Za-z0-9_-].

    Multiple samples are checked to ensure we don't depend on a single
    lucky string; entropy is enforced by the underlying ``secrets``
    module.
    """
    import re
    import string
    allowed = set(string.ascii_letters + string.digits + "-_")
    for _ in range(16):
        raw = generate_api_key()
        assert len(raw) == 43, f"unexpected raw key length {len(raw)}"
        assert all(c in allowed for c in raw), (
            f"raw key contains non-URL-safe characters: {raw!r}"
        )
        # SHA-256 hex is always 64 chars.
        h = hash_api_key(raw)
        assert len(h) == 64
        assert re.fullmatch(r"[0-9a-f]{64}", h)


def test_raw_key_never_persisted_only_hash_on_disk():
    """Hard requirement: only SHA-256 hash must be on disk; raw key must
    not appear in any persisted column."""
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            raw = generate_api_key()
            user, _, cred, _ = _bootstrap_human_credential(
                db,
                username=f"sec-{uuid.uuid4().hex[:8]}",
                workspace="Raw Key Workspace",
                role=Role.SECRETARY,
                raw_key=raw,
            )
            # Re-read the credential from a fresh session.
            db.close()
            db = factory()
            rows = db.query(ApiCredential).all()
            for row in rows:
                assert raw not in (row.key_hash or "")
                assert raw not in (row.purpose or "")
                assert raw not in str(row.id)
        finally:
            db.close()


# ============================================================================
# F) Legacy scripts/create_api_key.py deprecation
#
# The legacy helper is a stub that prints a deprecation error and
# exits 2. We assert that here so a future refactor cannot silently
# resurrect the legacy code path against the V1 schema.
# ============================================================================


def test_legacy_create_api_key_script_is_a_deprecation_stub(tmp_path, monkeypatch):
    """Running the legacy script must exit non-zero and point operators
    at the V1-aware helpers; it must not touch the DB."""
    repo_root = Path(__file__).resolve().parent.parent
    script = repo_root / "scripts" / "create_api_key.py"
    assert script.exists(), "legacy script should still exist (as a deprecation marker)"
    # Isolate PYTHONPATH so the script can't accidentally pick up
    # production env / DB.
    monkeypatch.delenv("DATABASE_URL", raising=False)
    result = subprocess.run(
        [sys.executable, str(script), "--username", "x", "--role", "admin"],
        capture_output=True, text=True,
        env={"PATH": os.environ.get("PATH", "")},
        cwd=str(tmp_path),
    )
    assert result.returncode == 2, (
        f"legacy script should exit 2 (deprecation), got "
        f"{result.returncode}: stdout={result.stdout!r} stderr={result.stderr!r}"
    )
    assert "DEPRECATED" in result.stderr
    assert "create_v1_api_key.py" in result.stderr


# ============================================================================
# G) SystemPrincipal contract
#
# Unit-test the dataclass invariants directly so a future refactor of
# app.core.permissions cannot silently break the "SYSTEM is not a
# Principal" guarantee.
# ============================================================================


def test_system_principal_is_not_a_principal_instance():
    """isinstance(SystemPrincipal, Principal) must be False — that is
    the canonical test ``require_role`` uses to refuse SYSTEM callers
    on Human-bound endpoints."""
    from app.core.permissions import SystemPrincipal
    assert not issubclass(SystemPrincipal, Principal)
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            _, cred, _ = _bootstrap_system_credential(db)
            sp = SystemPrincipal(credential=cred, name=cred.purpose)
            assert not isinstance(sp, Principal)
        finally:
            db.close()


def test_v1_system_purpose_allowlist_is_exactly_one():
    """V1_SYSTEM_PURPOSES is intentionally narrow: only 'internal:scheduler'
    is accepted today. Adding more SYSTEM purposes requires an explicit
    update to ``app.v1.models.base.V1_SYSTEM_PURPOSES`` — this test
    catches accidental over-broadening."""
    assert V1_SYSTEM_PURPOSES == frozenset({"internal:scheduler"})


# ============================================================================
# H) V1_SYSTEM_PURPOSES allow-list is enforced (defence in depth).
# ============================================================================


def test_active_system_with_unknown_purpose_is_rejected():
    """An active SYSTEM credential with an unknown purpose must NOT
    authenticate as a SYSTEM principal — the dep layer is the last line
    of defence even if the bootstrap script is bypassed."""
    from fastapi import HTTPException
    with v1_engine_ctx():
        factory = get_session_factory()
        db = factory()
        try:
            user = (
                db.query(User)
                .filter(User.username == SYSTEM_SENTINEL_USERNAME)
                .one_or_none()
            )
            if user is None:
                user = User(
                    telegram_user_id=None,
                    username=SYSTEM_SENTINEL_USERNAME,
                    display_name="S",
                    default_language="en-US",
                )
                db.add(user)
                db.flush()
            raw = generate_api_key()
            db.add(ApiCredential(
                user_id=user.id,
                key_hash=hash_api_key(raw),
                is_active=True,
                principal_type=V1PrincipalType.SYSTEM.value,
                purpose="internal:not-allowed",
            ))
            db.commit()
            with pytest.raises(HTTPException) as exc:
                get_system_principal(authorization=f"Bearer {raw}", db=db)
            assert exc.value.status_code == 401
        finally:
            db.close()
